python SanText-main/run_glue.py \
--model_name_or_path bert-base-uncased \
--task_name qnli \
--do_train \
--do_eval \
--data_dir selective-normal-qnli/eps_8.00 \
--max_seq_length 128 \
--per_device_train_batch_size 64 \
--per_device_eval_batch_size 64 \
--learning_rate 2e-5 \
--num_train_epochs 2.0 \
--output_dir ./tmp/qnli-sanitize/ \
--overwrite_output_dir \
--overwrite_cache \
--save_steps 2000